<?php

namespace UserFrosting;

/**
 * Description of ProxyController
 *
 * @author Florian
 */
class ProxyController extends \UserFrosting\BaseController {

    public function __construct($app) {
        $this->_app = $app;
    }

    public function genSquidguardConf() {

        $tab = "\t";

        $conf = "################################" . PHP_EOL;
        $conf.="#SquidGuard configuration file" . PHP_EOL;
        $conf.="#Generated by IHMSQUID" . PHP_EOL;
        $conf.="################################" . PHP_EOL;
        $conf.=PHP_EOL;
        $conf.=PHP_EOL;
        $conf.="dbhome /var/lib/squidguard/db/blacklists" . PHP_EOL;
        $conf.="logdir /var/log/squidguard/" . PHP_EOL;
        $conf.=PHP_EOL;
        $conf.=PHP_EOL;

        //time
        $horaires = MySqlWorkingHoursLoader::fetch("1");
        $conf.="################################" . PHP_EOL;
        $conf.="#Working Hours" . PHP_EOL;
        $conf.="################################" . PHP_EOL;
        $conf.="time WorkingHours {" . PHP_EOL;
        $conf.=$tab . "weekly mtwhf " . $horaires->hourstartam . "-" . $horaires->hourendam . PHP_EOL;
        $conf.=$tab . "weekly mtwhf " . $horaires->hourstartpm . "-" . $horaires->hourendpm . PHP_EOL;
        $conf.="}" . PHP_EOL;
        $conf.=PHP_EOL;
        $conf.=PHP_EOL;

        //Src
        $salles = MySqlSalleLoader::fetchAll();
        $ips_formateur = "";
        $src = "";
        foreach ($salles as $salle) {
            //Récup ip formateur
            $ips_formateur .= $salle->ip_formateur . " ";

            //Pour chaque salle, création du src
            $src.="src " . str_replace(" ", "_", $salle->name) . " {" . PHP_EOL;
            $src.=$tab . "ip $salle->network/$salle->mask_cidr" . PHP_EOL;
            $src.="}" . PHP_EOL;
            $src.=PHP_EOL;
        }

        $conf.="################################" . PHP_EOL;
        $conf.="#SRC" . PHP_EOL;
        $conf.="################################" . PHP_EOL;
        $conf.="src formateurs {" . PHP_EOL;
        $conf.=$tab . "ip " . $ips_formateur . PHP_EOL;
        $conf.="}" . PHP_EOL;
        $conf.=PHP_EOL;

        $conf.=$src;
        $conf.=PHP_EOL;

        //dest
        $categories = MySqlBlacklistCategoriesLoader::fetchAll();
        $conf.="################################" . PHP_EOL;
        $conf.="#DEST" . PHP_EOL;
        $conf.="################################" . PHP_EOL;

        foreach ($categories as $category) {
            $conf.="dest $category->category_name {" . PHP_EOL;
            $conf.=$tab . "domainlist $category->category_name/domains" . PHP_EOL;
            $conf.=$tab . "urllist $category->category_name/urls" . PHP_EOL;
            $conf.=$tab . "expressionlist $category->category_name/expressions" . PHP_EOL;
            $conf.="}" . PHP_EOL;
            $conf.=PHP_EOL;
        }

        //blacklist et whitelist définies dans l'application
        $conf.="dest blacklist_ihmsquid {" . PHP_EOL;
        $conf.=$tab . "domainlist blacklist_ihmsquid/domains" . PHP_EOL;
        $conf.=$tab . "urllist blacklist_ihmsquid/urls" . PHP_EOL;
        $conf.=$tab . "expressionlist blacklist_ihmsquid/expressions" . PHP_EOL;
        $conf.="}" . PHP_EOL;
        $conf.=PHP_EOL;
        $conf.="dest whitelist_ihmsquid {" . PHP_EOL;
        $conf.=$tab . "domainlist whitelist_ihmsquid/domains" . PHP_EOL;
        $conf.=$tab . "urllist whitelist_ihmsquid/urls" . PHP_EOL;
        $conf.=$tab . "expressionlist whitelist_ihmsquid/expressions" . PHP_EOL;
        $conf.="}" . PHP_EOL;
        $conf.=PHP_EOL;

        //Niveaux de filtrage personnalisé
        $customfilters = MySqlCustomConfLoader::fetchAllExceptStandard();
        foreach ($customfilters as $customfilter) {
            $conf.="dest " . str_replace(" ", "_", $customfilter->name) . " {" . PHP_EOL;
            $conf.=$tab . "domainlist " . str_replace(" ", "_", $customfilter->name) . "/domains" . PHP_EOL;
            $conf.=$tab . "urllist " . str_replace(" ", "_", $customfilter->name) . "/urls" . PHP_EOL;
            $conf.=$tab . "expressionlist " . str_replace(" ", "_", $customfilter->name) . "/expressions" . PHP_EOL;
            $conf.="}" . PHP_EOL;
            $conf.=PHP_EOL;
        }
        //
        //Ecriture du fichier de conf en local
        var_dump($conf);
        shell_exec("echo \"$conf\" > /tmp/squidguard.conf");
    }

}

?>
